create splash migration store and service file
Unleash/unleash pull request #1095
Opened 2021-11-08 15:32 UTC by ykhedher

2021-11-09 21:42 UTC, ykhedher commented
![](https://github.trello.services/images/mini-trello-icon.png) [Splash Implementation](https://trello.com/c/SZyBRWwS/590-splash-implementation)

2021-11-11 08:49 UTC, FredrikOseberg requested changes
This looks good! Just a few things from my side before we merge. For example, I don't think it makes sense to have an endpoint to create a splash for a user, because essentially we want to control when we show splash screens - which will require us to run a migration or something similar to update the splash table for all users. 

So I think we just need to option to update a given splash id for a user.

2021-11-11 08:49 UTC, FredrikOseberg commented on src/lib/routes/admin-api/user-splash-controller.ts
> +    private async recordSplash(
This does the same as the /:id endpoint. I think the id endpoint makes more sense in this context.

2021-11-11 08:49 UTC, FredrikOseberg commented on src/lib/routes/admin-api/user-splash-controller.ts
> +    private async updateSplashSettings(
We should return 400 bad request here if seen is not present in the body.

2021-11-11 08:49 UTC, FredrikOseberg commented on src/lib/services/user-splash-service.ts
> +            const splashs = await (
Double await?

2021-11-11 08:51 UTC, FredrikOseberg commented on src/migrations/20211109103930-add-splash-entry-for-users.js
> +exports.up = function (db, cb) {
@chriswk Can we write this in raw SQL?

2021-11-12 07:59 UTC, chriswk commented on src/migrations/20211109103930-add-splash-entry-for-users.js
> +exports.up = function (db, cb) {
```
INSERT INTO user_splash(splash_id, user_id, seen) SELECT 'envrironment', u.id, false FROM users u
```
Should do the trick

2021-11-12 08:01 UTC, chriswk requested changes
Added a suggestion for the migration

2021-11-12 09:40 UTC, ykhedher commented on src/migrations/20211109103930-add-splash-entry-for-users.js
> +exports.up = function (db, cb) {
Yep thanks 👍🏻

2021-11-12 10:43 UTC, FredrikOseberg requested changes
Just a small comment here, then I think this is good to go.

2021-11-12 10:43 UTC, FredrikOseberg commented on src/lib/routes/admin-api/user-splash-controller.ts
> +            ...req.body,
We don't need to accept anything from ```req.body``` here.

2021-11-12 12:16 UTC, FredrikOseberg requested changes

2021-11-12 12:16 UTC, FredrikOseberg commented on src/lib/services/user-splash-service.ts
> +            return [];
This function is expected to return an object.

2021-11-22 10:49 UTC, chriswk approved these changes
The migration looks good now, as well as the exists using the select 1 trick is :+1: .

Gogo

2021-11-23 18:57 UTC, FredrikOseberg approved these changes
LGTM

2021-11-23 19:26 UTC, merged