Update readme
Unleash/unleash pull request #1488
Opened 2022-04-07 12:47 UTC by thomasheartman

2022-04-08 07:38 UTC, thomasheartman commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update README on GitHub](https://trello.com/c/eKuEDgUo/1019-update-readme-on-github)

2022-04-08 07:39 UTC, chriswk approved these changes
Looks good!

2022-04-08 07:40 UTC, chriswk commented on README.md
> +[Get image from Nicolae here]
TODO: This one needs fixing before we merge this

2022-04-08 07:41 UTC, chriswk requested changes
Putting a blocker until we no longer have the reminder to ask Nicolae about image.

2022-04-08 11:27 UTC, thomasheartman commented
@chriswk For sure! I'd just forgotten to mark the PR as draft. But the reminder is gone now and the PR is ready 🚂

2022-04-11 07:46 UTC, chriswk approved these changes
LGTM :)

2022-04-11 07:47 UTC, merged