fix: use getCreatedBy to set created by on events stored
Unleash/unleash pull request #1648
Opened 2022-06-01 08:07 UTC by chriswk

Thomas found that project-change-events are not stored if created by users without a username. this fix makes sure that we either use email or username to store who makes the changes.

2022-06-01 08:20 UTC, chriswk commented
I've added a test confirming that changing projects adds an event to the event store.

2022-06-01 09:10 UTC, thomasheartman requested changes
Thanks for helping me diagnose this! 🙏🏼  The changes look like a step forward for sure 😄  

However, I think that the root cause here may be that the `User` class (in  User.ts)  says that `username` is of type `string` (and _not_ `string | undefined`). Because the changeProject function accepts a `User` object as a parameter, `user.username` shows up as `string` and we don't get any type checking for it. Can we leverage the type system here somehow? It might suffice to change the parameter type to IUser, whose `username` and `email` props are both optional, but that introduces another problem: the code doesn't know that a user will always have _at least one_ of them 🤔 

I'd love to explore some ways to fix this before getting it in.

2022-06-01 10:29 UTC, thomasheartman commented
Something like that exactly, yeah! Except it's not always strictly one or the other. A user _may_ have both, right? But if TS ignores the extra properties, then it should be fine

2022-06-02 11:45 UTC, ivarconr approved these changes

2022-06-02 11:50 UTC, thomasheartman approved these changes
Approved after further discussion. Let's create a card to address this in a more thorough manner later 🎫

2022-06-02 11:52 UTC, merged