fix: Issue #1444 - API import with drop=true deletes existing client keys
Unleash/unleash pull request #1668
Opened 2022-06-04 06:11 UTC by szczepad

## About the changes
The goal of this PR was to not drop existing api-tokens on an import with the drop=true flag.
The reason why these api-tokens have been dropped was the fact, that environments serve as foreign-key on the api-tokens table. This foreign key was setup in a way in which a deletion of an environment (which is part of drop=true) would cascade into api-tokens.

To solve this issue the constraint described above was removed. This leads to api-tokens never being deleted if drop=true is set.
In order to not store unecessary api-tokens a check during import of configuration was added, which removes all tokens which do not belong to an existing environment.

Closes #1444  .

### Important files
The main files of the PR are the database migration in 

The main files of this PR are 
- the database-migration in src/migrations/20220528143630-dont-cascade-environment-deletion-to-apitokens.js , which handle not deleting the api-keys on an import with drop=true
- the changes in src/lib/services/state-service.ts which handle the cleanup of api-tokens after an import.

## Discussion points

2022-06-07 12:13 UTC, thomasheartman reviewed
Thanks so much for checking out the viability of this and finding a way to make it work! 🙌🏼  I'm generally in favor of this change, but dropping the DB constraints gives me pause. I'll loop in someone else with more insight into the db structure, so that we can work through this together ☺️  I've added a few comments inline that I think may be small errors; feel free to tell me if they're not!

2022-06-07 12:13 UTC, thomasheartman commented on src/test/e2e/api/admin/state.e2e.test.ts
> +    console.log(apiTokens);
Is this console log intentional or left in by mistake? Unless it serves a specific purpose, we probably want to remove it 💁🏼

2022-06-07 12:13 UTC, thomasheartman commented on src/migrations/20220528143630-dont-cascade-environment-deletion-to-apitokens.js
> +          ALTER TABLE api_tokens DROP CONSTRAINT api_tokens_environment_fkey;
Should both these commands be the same? If the up command drops the constraint, shouldn't the down command create that constraint?

2022-06-07 13:27 UTC, chriswk commented
Having looked through this, and seeing that you are indeed still deleting tokens for environments that did not get readded with the import. I tend towards a :+1: . As Thomas said earlier, thanks so much for taking the time to making the effort.

2022-06-07 13:28 UTC, chriswk requested changes
I'm missing a test for the environment service. Does api-tokens still get deleted if I delete an environment using the environment-service, rather than during the import/export code?

2022-06-07 19:55 UTC, szczepad commented
Thanks for the valuable Feedback! :)
Indeed I'm currently not checking on the environment-service. Will add that quickly. :)

2022-06-09 04:56 UTC, szczepad commented
Hey @chriswk,

> I'm missing a test for the environment service. Does api-tokens still get deleted if I delete an environment using the environment-service, rather than during the import/export code?

I just had a look on the environment-service. It seems like currently there's no functionality to delete an environment exposed by that service, but only to remove environments from projects. In the latter I suppose it wouldn't make sense to delete the api-tokens as the correlating environment should still be in the db and usable.

Should I add the functionality to delete environments, to avoid unexpected behaviour regarding the deletion of api-tokens in the future? If not, all other remarks for this PR should be resolved.

Thanks! :)

2022-06-09 06:50 UTC, chriswk commented
Agreed, that removing an environment from a project is not enough to warrant removing the API key. I won't expect you to expand environment-service, so I'd say we're good to go.

2022-06-09 06:51 UTC, chriswk approved these changes
Thank you for this. :)

2022-06-09 14:56 UTC, merged