open-api addon controller
Unleash/unleash pull request #1721
Opened 2022-06-15 11:17 UTC by andreas-unleash

Implemented OAS for the models and routes of the addon controller 
## About the changes

Closes # .

### Important files

## Discussion points

2022-06-17 07:19 UTC, andreas-unleash commented
![](https://github.trello.services/images/mini-trello-icon.png) [OpenApi: Addon controller](https://trello.com/c/KpnLZsfx/1292-openapi-addon-controller)

2022-06-17 09:59 UTC, olav requested changes

2022-06-17 09:59 UTC, olav commented on src/lib/openapi/spec/addon-definition-schema.ts
> +export const addonDefinitionSchema = {
Maybe we could call this `addonTypeSchema`, slightly shorter.

2022-06-17 09:59 UTC, olav commented on src/lib/openapi/spec/parameter-definition-schema.ts
> +export const parameterDefinitionSchema = {
Could call this `addonParameterSchema`, since it's only used with addons.

2022-06-17 09:59 UTC, olav commented on src/lib/openapi/spec/addon-definition-schema.ts
> +export type AddonDefinitionSchema = FromSchema<typeof addonDefinitionSchema>;
Usually put a linebreak before the type.

2022-06-17 09:59 UTC, olav commented on src/lib/openapi/spec/addon-schema.ts
> +            additionalProperties: true,
Should this use the parameters schema? Not sure if it's the same thing.

2022-06-17 09:59 UTC, olav commented on src/lib/openapi/spec/get-addons-schema.ts
> +export const getAddonsSchema = {
Could be called `addonsSchema` to match the other schemas.

2022-06-17 09:59 UTC, olav commented on src/lib/routes/admin-api/addon.ts
> +            path: PATH,
The path should be `''` to avoid a required trailing slash.

2022-06-17 09:59 UTC, olav commented on src/lib/routes/admin-api/addon.ts
> +                        200: createResponseSchema('addonSchema'),
Should use the collection schema.

2022-06-17 09:59 UTC, olav commented on src/lib/routes/admin-api/addon.ts
>      async getAddons(req: Request, res: Response): Promise<void> {
Should add the generated type to the response.

2022-06-22 07:24 UTC, olav requested changes

2022-06-22 07:24 UTC, olav commented on src/lib/routes/admin-api/addon.ts
> +            path: PATH,
Should be `path: ''` to avoid requiring a trailing slash.

2022-06-22 10:49 UTC, merged