UX additions to groups SSO syncing
Unleash/unleash pull request #2200
Opened 2022-10-18 10:56 UTC by sellinjaanus

When group syncing is disabled, now gray infromation box is displayed.
Also now in group members list, the person who added the person to group, is displayed.

2022-10-18 12:32 UTC, nunogois requested changes
LGTM - Noticed some little things we might want to change before merging.

2022-10-18 12:32 UTC, nunogois commented on frontend/src/component/admin/groups/GroupForm/GroupForm.tsx
> +                    )}
Only need to wrap `uiConfig.flags.syncSSOGroups` in the `Boolean()`, not `isOss()`

2022-10-18 12:32 UTC, nunogois commented on frontend/src/component/admin/groups/GroupForm/GroupForm.tsx
> +                                <>
No need to wrap in a fragment, only 1 parent container: `StyledDescriptionBlock`.

2022-10-19 11:26 UTC, sjaanus commented on frontend/src/component/admin/groups/GroupForm/GroupForm.tsx
> +    };
Good idea! Done.

2022-10-19 13:23 UTC, nunogois approved these changes
LGTM! 
I found some very small nitpicks in case you want to have a look, but I'm fine with this getting merged 👍

2022-10-19 13:23 UTC, nunogois commented on frontend/src/component/admin/groups/GroupForm/GroupForm.tsx
> +                                            View SSO configuration{' '}
Unneeded extra space?
```suggestion
                                            View SSO configuration
```

2022-10-19 13:23 UTC, nunogois commented on frontend/src/component/admin/groups/GroupForm/GroupForm.tsx
> +                            condition={Boolean(isGroupSyncingEnabled)}
No need, it's already a boolean.
```suggestion
                            condition={isGroupSyncingEnabled}
```

2022-10-20 07:47 UTC, merged