Update rootRole on login (#2243)
Unleash/unleash pull request #2244
Opened 2022-10-24 17:47 UTC by dev-slatto

## About the changes
Don't think this needs much explanation. It will only update the user object on SSO authentication when a rootRole is present on the User object. This should solve the issues as mentioned in #2243 

Closes #2243 .

2022-10-25 17:43 UTC, ivarconr requested changes
We can not accept this change as it will be a breaking change to existing users of Unleash. We have two options:

1. Introduce a new method for the new behavior 
2. document how to deal with this. After all this require custom code anyway. 

I lean toward option 2.

2022-10-26 03:59 UTC, dev-slatto commented
@ivarconr Will it do that? We're introducing this as a new optional variable on the update user object so that if it's not explicitly set, it should not do anything? That's also the reason I created it as a dedicated if block just targeting the rootRole if updated. I don't know the codebase that good so not quite sure on the intended flow, but shouldn't there be a way when using an customAuthHandler to have the data from that being the truth of access? 

If there is a way to do this that I don't know about I would be happy to learn 😄

2022-10-26 13:57 UTC, ivarconr commented
> I don't know the codebase that good so not quite sure on the intended flow, but shouldn't there be a way when using an customAuthHandler to have the data from that being the truth of access?

your custom auth handler can just call [updateUser()](https://github.com/Unleash/unleash/blob/main/src/lib/services/user-service.ts#L231) with correct rootRole to achieve the desired behavior.

2022-10-28 07:46 UTC, dev-slatto commented
Thanks! Then I'll do it in the auth handler 😄

2022-10-28 07:46 UTC, closed without merging