docs: move sso how to guides to the how-to folder
Unleash/unleash pull request #2323
Opened 2022-11-03 10:38 UTC by sighphyre

We're in the process of moving how-to guides into the how-to folder, where they belong. This continues that work and shifts the how to guides for SSO to the correct place and gives them appropriate names

2022-11-03 11:31 UTC, thomasheartman requested changes
You're doing the proverbial Lord's work here, Simon! 🙌🏼  This looks great, but changing the file locations also changes their URL, so you'll need to add the corresponding redirects:

Check out the `plugin-client-redirects` in `website/docusaurus.config.js`. Just add the old path and the new ones. Be aware that the redirects aren't active in development mode, so you'll need to use a production build to test that they work. There's more info in [docusaurus'  plugin-client-redirect docs](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects/).

Otherwise, I've also added suggestions to use docusaurus' admonitions for availability and deprecation notices. It's not really part of the relocation, but it might be nice to do regardless.

2022-11-03 11:31 UTC, thomasheartman commented on website/docs/how-to/how-to-add-sso-google.md
> +> Single Sign-on via the Google Authenticator provider is deprecated. We recommend using [OpenID Connect](./how-to-add-sso-open-id-connect.md) instead.
```suggestion
:::caution Deprecation notice

Single Sign-on via the Google Authenticator provider is deprecated. We recommend using [OpenID Connect](./how-to-add-sso-open-id-connect.md) instead.

:::
```

2022-11-03 11:31 UTC, thomasheartman commented on website/docs/how-to/how-to-add-sso-saml-keycloak.md
>  > The **Single-Sign-On capability** is only available for customers on the Enterprise subscription. Check out the [Unleash plans](https://www.getunleash.io/plans) for details.
```suggestion
:::note Availability

The **Single-Sign-On capability** is only available for customers on the Enterprise subscription. Check out the [Unleash plans](https://www.getunleash.io/plans) for details.

:::
```

2022-11-03 11:31 UTC, thomasheartman commented on website/docs/how-to/how-to-add-sso-open-id-connect.md
>  > The **Single-Sign-On capability** is only available for customers on the Enterprise subscription. Check out the [Unleash plans](https://www.getunleash.io/plans) for details.
```suggestion
:::note Availability

The **Single-Sign-On capability** is only available for customers on the Enterprise subscription. Check out the [Unleash plans](https://www.getunleash.io/plans) for details.

:::
```

2022-11-03 11:31 UTC, thomasheartman commented on website/docs/how-to/how-to-add-sso-saml.md
>  > The **Single-Sign-On capability** is only available for customers on the Enterprise subscription. Check out the [Unleash plans](https://www.getunleash.io/plans) for details.
```suggestion
:::note Availability

The **Single-Sign-On capability** is only available for customers on the Enterprise subscription. Check out the [Unleash plans](https://www.getunleash.io/plans) for details.

:::
```

2022-11-04 06:34 UTC, sighphyre commented
> You're doing the proverbial Lord's work here, Simon!

Gosh that made me blush. I think it's time, yeah, if we're going to go forwards with new patterns, let's go forwards. Happy to help

>Check out the plugin-client-redirects in website/docusaurus.config.js. Just add the old path and the new ones. Be aware that the redirects aren't active in development mode, so you'll need to use a production build to test that they work. There's more info in [docusaurus' plugin-client-redirect docs](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects/).

> Otherwise, I've also added suggestions to use docusaurus' admonitions for availability and deprecation notices. It's not really part of the relocation, but it might be nice to do regardless.

Amazing, thank you! I will take a look today, I figured there was probably something I was missing here so thanks for the pointer!

2022-11-11 08:18 UTC, thomasheartman approved these changes
This looks good to me now 😄

2022-11-11 08:23 UTC, thomasheartman commented
I've also gone through and tested all the redirects you've added, by the way. They work as expected 🥳

2022-11-11 08:58 UTC, sighphyre commented
> I've also gone through and tested all the redirects you've added, by the way. They work as expected partying_face

You're amazing, thank you!

2022-11-14 12:11 UTC, merged