feat: collaboration mode API cleanup
Unleash/unleash pull request #3357
Opened 2023-03-21 08:46 UTC by kwasniew

## About the changes
Removing confusing nullable field. Making wording consistent

### Important files

## Discussion points

2023-03-21 09:00 UTC, thomasheartman requested changes
Thanks for cleaning up! 🙌🏼  

I think the description could change a little bit to be clearer, but the best would probably be to link to the docs. 

I've added a suggestion for the first instance, but I think the same suggestion should be added to the changes in `src/lib/openapi/spec/project-overview-schema.ts` and `src/lib/openapi/spec/project-schema.ts` too.

To be clear: I think the most future-proof solution is to simply link to the docs, but if you think project mode will only ever affect whether you can create change requests or not, then the longer version might be appropriate.

2023-03-21 12:59 UTC, kwasniew commented on src/lib/openapi/spec/health-overview-schema.ts
> +                'A collaboration mode of the project affecting if non-project members can submit change requests',
I like the first explicit variant. If we discover a different need for the project mode we can update later.

2023-03-23 07:53 UTC, thomasheartman approved these changes
Nice; I like it! But just so we're clear: is collaboration mode planned to control more than change requests?

2023-03-23 13:13 UTC, kwasniew commented
@thomasheartman we don't know yet. For now it's only for change requests. We may or may not discover other use cases over time. I like to think of it as an option.

2023-03-23 13:13 UTC, merged