Fix: change request info
Unleash/unleash pull request #3971
Opened 2023-06-13 15:02 UTC by Tymek

## About the changes
- fixed spacing in sidebar
- consolidated info into one banner

closes [#1-969/change-requests-ui-inconsistency](https://linear.app/unleash/issue/1-969/change-requests-ui-inconsistency)

2023-06-16 11:35 UTC, kwasniew requested changes

2023-06-16 11:35 UTC, kwasniew commented on frontend/src/component/layout/MainLayout/DraftBanner/DraftBanner.tsx
> +                    {changeRequests.reduce(
I wouldn't put low level reduce inside the component. Scripting outside of the components with intention revealing names

2023-06-16 11:35 UTC, kwasniew commented on frontend/src/component/layout/MainLayout/DraftBanner/DraftBanner.tsx
> +                            changeRequests.length === 1 &&
missing intention revealing name. I recommend extract method refactoring

2023-06-16 11:35 UTC, kwasniew commented on frontend/src/component/layout/MainLayout/DraftBanner/DraftBanner.tsx
> +                            {
another extract refactoring because it's too dense here

2023-06-16 11:35 UTC, kwasniew commented on frontend/src/component/layout/MainLayout/DraftBanner/DraftBanner.tsx
> +                ['Draft', 'In review', 'Approved'].includes(changeRequest.state)
why is approved and in review added to drafts variable? it doesn't make sense to me

2023-06-30 11:00 UTC, sjaanus approved these changes
LG , just minor tweak

2023-06-30 11:00 UTC, sjaanus commented on frontend/src/component/layout/MainLayout/DraftBanner/DraftBanner.tsx
> +    const count = changeRequests.reduce(
Can we name it more explicit, count of what?

2023-07-03 18:19 UTC, kwasniew approved these changes
Non blocking approve, but I'd add tests since there's so much untested UI logic. Also not sure why we're doing type casting in 2 places.

2023-07-03 18:19 UTC, kwasniew commented on frontend/src/component/layout/MainLayout/DraftBanner/DraftBanner.tsx
>  const DraftBannerContent: FC<{
Too much untested logic

2023-07-04 07:09 UTC, merged