feat: add usage info to project role deletion dialog
Unleash/unleash pull request #4464
Opened 2023-08-10 06:28 UTC by daveleek

## About the changes

Adds projects user and group -usage information to the dialog shown when user wants to delete a project role

![Skjermbilde 2023-08-09 kl  15 47 57](https://github.com/Unleash/unleash/assets/707867/aeb198d7-95f7-484e-9d5d-58482b7a20cf)

2023-08-11 11:11 UTC, nunogois requested changes
Looking good, but I think we can still do better, so I left a few comments. 
Let me know if you need help tackling them 👍

2023-08-11 11:11 UTC, nunogois commented on src/lib/types/stores/access-store.ts
> +export interface IProjectUsageCount {
```suggestion
export interface IProjectRoleUsage {
```

2023-08-11 11:11 UTC, nunogois commented on src/lib/types/stores/access-store.ts
> +    userCount: number;
```suggestion
    userCount: number;
    serviceAccountCount: number;
```

2023-08-11 11:11 UTC, nunogois commented on src/lib/services/access-service.ts
> +
I think this can be simplified after applying the other suggestions.

2023-08-11 11:11 UTC, nunogois commented on src/lib/services/project-service.ts
> +    async getProjectsByRole(roleId: number): Promise<IProjectRoleUsage[]> {
```suggestion
    async getProjectRoleUsage(roleId: number): Promise<IProjectRoleUsage[]> {
```

2023-08-11 11:17 UTC, nunogois commented on frontend/src/component/admin/roles/RolesTable/RoleDeleteDialog/RoleDeleteDialogProjectRoles/RoleDeleteDialogProjectRoleTable.tsx
> +                        <HighlightCell value={item.project} />
Perhaps this could be a link to the project? 🤔

2023-08-11 11:17 UTC, nunogois commented on frontend/src/component/admin/roles/RolesTable/RoleDeleteDialog/RoleDeleteDialogProjectRoles/RoleDeleteDialogProjectRoleTable.tsx
> +                },
I think we should add service accounts as a separate column here.

2023-08-11 11:20 UTC, daveleek commented on frontend/src/component/admin/roles/RolesTable/RoleDeleteDialog/RoleDeleteDialog.tsx
> +    if (role?.type === 'custom') {
Perfect, thank you!

2023-08-11 12:01 UTC, daveleek commented on frontend/src/component/admin/roles/RolesTable/RoleDeleteDialog/RoleDeleteDialogProjectRoles/RoleDeleteDialogProjectRoles.tsx
> +};
Good point! will do

2023-08-11 12:01 UTC, daveleek commented on frontend/src/component/admin/roles/RolesTable/RoleDeleteDialog/RoleDeleteDialogRootRoles/RoleDeleteDialogRootRoles.tsx
> +};
Indeed! thanks!

2023-08-16 06:37 UTC, daveleek commented on src/lib/db/access-store.ts
> +
Done, and done

2023-08-16 07:48 UTC, chriswk approved these changes
Nice. Looks good to go.

2023-08-17 07:43 UTC, merged