Intro React Tutorial
Unleash/unleash pull request #5579
Opened 2023-12-08 14:53 UTC by nnennandukwe

## About the changes

Adding in an initial React tutorial with Unleash! This includes installing Unleash, creating a React application with Vite, then integrating Unleash to use with a CSS-focused feature toggle.

### Important files

- New File: `website/docs/feature-flag-tutorials/react/implementing-feature-flags.md`
- Added new tutorial to navigation in `sidebars.js` and `docusaurus.config.js`

## Discussion points

There is a lot of room to make more advanced use case additions to this React tutorial. For example, addressing SSR.
I think that'd be good for a future iteration to be helpful to the community.

2023-12-08 19:57 UTC, dgorton commented on website/docs/feature-flag-tutorials/react/implementing-feature-flags.md
> +yard dev
Should be `yarn`

2023-12-08 20:01 UTC, dgorton requested changes
Looking good - two minor adjustments: 1 typo fix and adding a screenshot

2023-12-08 20:01 UTC, dgorton commented on website/docs/feature-flag-tutorials/react/implementing-feature-flags.md
> +
Please add a screenshot here as well so people have a visual comparison

2023-12-11 17:17 UTC, nnennandukwe commented on website/docs/feature-flag-tutorials/react/implementing-feature-flags.md
> +yard dev
Woops! Thanks for catching that!

2023-12-11 17:17 UTC, nnennandukwe commented on website/docs/feature-flag-tutorials/react/implementing-feature-flags.md
> +
Ah, yes I have one. Thanks, will update.

2023-12-11 18:07 UTC, merged