Sveltekit tutorial
Unleash/unleash pull request #6538
Opened 2024-03-13 14:22 UTC by alvinometric

Simple Sveltekit tutorial

2024-03-13 17:42 UTC, nnennandukwe requested changes
Great work @alvinometric ! 👏 

I've added quite a few comments that mostly cover:
- structure (sentences & layout of the doc)
- any clarification needed on the "what" and "how" in your steps

Those comments are to make sure we can be aligned on how we want to convey information to developers and ensure we're using a good structure that is easy to follow and easily discoverable when people search for SvelteKit feature flag things (while still using our own voice in the tutorials). 

Additional suggestions:
- I'd recommend replacing references of "Sveltekit" with "SvelteKit" in the doc. Whichever one is the official capitalization for the name. To my knowledge, it's "SvelteKit".
- Include an architectural diagram of how the SvelteKit app will be hooked up to the SDK and Unleash. I personally use Excalidraw for the diagram and you can use this as reference. Replace "React app" with "SvelteKit app" and the feature flag on-and-off states specific to this tutorial like so:
<img width="888" alt="Screenshot 2024-03-13 at 1 37 42 PM" src="https://github.com/Unleash/unleash/assets/22972707/02c13bec-8465-4fc6-9ce4-c1a1599e6799">

2024-03-13 17:42 UTC, nnennandukwe commented on website/docs/feature-flag-tutorials/sveltekit/feature-flags-sveltekit.md
> +Enjoy, see you soon.
I'd suggest removing this line for now and maybe we can replace it with pointing devs to a link to other useful docs in the future. Example:

Take a look at our [insert link] documentation for a deeper dive into advanced use cases with Sveltekit.

2024-03-13 17:42 UTC, nnennandukwe commented on website/docs/feature-flag-tutorials/sveltekit/feature-flags-sveltekit.md
> +title: How to Implement Feature Flags in Sveltekit using Unleash
```suggestion
title: How to Implement Feature Flags in SvelteKit
```

2024-03-13 17:42 UTC, nnennandukwe commented on website/docs/feature-flag-tutorials/sveltekit/feature-flags-sveltekit.md
> +## Let's make a basic habits app
```suggestion
## Create a basic habits app
```

2024-03-13 17:42 UTC, nnennandukwe commented on website/docs/feature-flag-tutorials/sveltekit/feature-flags-sveltekit.md
> +We'll need a few more dependencies, let's install them now so it's out of the way.
```suggestion
We'll need a few more dependencies. You can install these in one command below:
```

2024-03-13 17:43 UTC, nnennandukwe commented on website/docs/feature-flag-tutorials/sveltekit/feature-flags-sveltekit.md
> +Now this is not a very user-friendly app. Let's add a few things:
```suggestion
We have the basics of the app set up, but we could make it more user-friendly. Let's add some more functionality:
```

2024-03-13 17:49 UTC, alvinometric commented on website/docs/feature-flag-tutorials/sveltekit/feature-flags-sveltekit.md
> +```svelte
It's the first comment in the file

2024-03-14 07:16 UTC, thomasheartman reviewed
Hey, Alvin! Nice work 🙌🏼 

Looks like Nnenna already gave you a very thorough and great review (👏🏼 👏🏼 👏🏼 ) and is probably a much better person for reviewing the content than I am.

However, I wanna chuck in a few comments on images, if you don't mind:

1. Please make sure they have a proper alt text, so that it's clear for people who can't see the image what it portrays. I'm assuming you're familiar with alt texts (it appears you've put in placeholders in a few of the places), but regardless, I have found this [blog post on alt texts from axess lab](https://axesslab.com/alt-texts/) to be a very useful primer/refresher on writing them.
2. We usually put images in the static/img directory and not right next to the doc. Of course, we can consider changing that, but we should probably do that in one go.

2024-03-14 07:16 UTC, thomasheartman commented on website/docs/feature-flag-tutorials/sveltekit/feature-flags-sveltekit.md
> +![Pasted image 20240202174256.png](./20240202174256.png)
This image needs an update as described in my general review comment.

2024-03-14 07:16 UTC, thomasheartman commented on website/docs/feature-flag-tutorials/sveltekit/feature-flags-sveltekit.md
> +![alt text](./proj.png)
Same here! The alt text appears to have been started but not finished?

2024-03-14 07:16 UTC, thomasheartman commented on website/docs/feature-flag-tutorials/sveltekit/feature-flags-sveltekit.md
> +![alt text](./feat.png)
And the same for this one.

2024-03-18 15:43 UTC, nnennandukwe approved these changes

2024-03-18 15:54 UTC, merged