.NET tutorial
Unleash/unleash pull request #7036
Opened 2024-05-10 12:14 UTC by alvinometric

Thank you so much to @daveleek for your help 🙏

2024-05-10 12:42 UTC, nnennandukwe approved these changes
Very clean and consistent! 👍  Awesome work @alvinometric

2024-05-14 06:28 UTC, daveleek commented on website/docs/feature-flag-tutorials/dotnet/implementing-feature-flags-dotnet.md
> +- The API token we created on our Unleash instance, feel free to create another one if you can’t find it.
I think you left out the create token part in the Unleash setup above? You do link to the docs further down, but it looks like you intended to guide the user through how to create a token :)

2024-05-14 06:29 UTC, daveleek requested changes
Nice one @alvinometric! You left out the bit about the API tokens, but apart from that good stuff!

2024-05-14 11:37 UTC, daveleek approved these changes
Good stuff Alvin!

2024-05-14 11:40 UTC, merged