Update feature-flag-best-practices.md
Unleash/unleash pull request #7801
Opened 2024-08-08 05:49 UTC by riboflavin

Updates to the Best Practices pages.

2024-08-12 17:31 UTC, ferrantim requested changes
Hi @riboflavin this looks generally good. I would like to add the images back and to fix the suggestions that I have made. Once you do that, you can resubmit the PR for approval.

2024-08-12 17:31 UTC, ferrantim commented on website/docs/topics/feature-flags/feature-flag-best-practices.md
> +### H3 \- 2\. Never expose PII. Follow the principle of least privilege.[​](https://docs.getunleash.io/topics/feature-flags/feature-flag-best-practices\#2-never-expose-pii-follow-the-principle-of-lea
```suggestion
###\- 2\. Never expose PII. Follow the principle of least privilege.[​](https://docs.getunleash.io/topics/feature-flags/feature-flag-best-practices\#2-never-expose-pii-follow-the-principle-of-least-privilege)
```

2024-08-12 17:31 UTC, ferrantim commented on website/docs/topics/feature-flags/feature-flag-best-practices.md
> +### H3 \- 3\. Evaluate flags as close to the user as possible. Reduce latency.[​](https://docs.getunleash.io/topics/feature-flags/feature-flag-best-practices\#3-evaluate-flags-as-close-to-the-user-as
```suggestion
### \- 3\. Evaluate flags as close to the user as possible. Reduce latency.[​](https://docs.getunleash.io/topics/feature-flags/feature-flag-best-practices\#3-evaluate-flags-as-close-to-the-user-as-possible-reduce-latency)
```

2024-08-12 17:31 UTC, ferrantim commented on website/docs/topics/feature-flags/feature-flag-best-practices.md
> +### H3 \- 4\. Scale Horizontally. Decouple reading and writing flags.[​](https://docs.getunleash.io/topics/feature-flags/feature-flag-best-practices\#4-scale-horizontally-decouple-reading-and-writing
```suggestion
### \- 4\. Scale Horizontally. Decouple reading and writing flags.[​](https://docs.getunleash.io/topics/feature-flags/feature-flag-best-practices\#4-scale-horizontally-decouple-reading-and-writing-flags)
```

2024-08-12 17:31 UTC, ferrantim commented on website/docs/topics/feature-flags/feature-flag-best-practices.md
> +### H3 \- 5\. Limit payloads. Feature flag payload should be as small as possible.[​](https://docs.getunleash.io/topics/feature-flags/feature-flag-best-practices\#5-limit-payloads-feature-flag-payloa
```suggestion
### \- 5\. Limit payloads. Feature flag payload should be as small as possible.[​](https://docs.getunleash.io/topics/feature-flags/feature-flag-best-practices\#5-limit-payloads-feature-flag-payload-should-be-as-small-as-possible)
```

2024-08-12 17:31 UTC, ferrantim commented on website/docs/topics/feature-flags/feature-flag-best-practices.md
> +### H3 \- 6\. Design for failure. Favor availability over consistency.[​](https://docs.getunleash.io/topics/feature-flags/feature-flag-best-practices\#6-design-for-failure-favor-availability-over-con
```suggestion
### \- 6\. Design for failure. Favor availability over consistency.[​](https://docs.getunleash.io/topics/feature-flags/feature-flag-best-practices\#6-design-for-failure-favor-availability-over-consistency)
```

2024-08-12 17:31 UTC, ferrantim commented on website/docs/topics/feature-flags/feature-flag-best-practices.md
> +   * Onboarding and Training: The entire feature flag solution, including API, UI, and SDKs, requires clear and comprehensive documentation, along with easy-to-understand examples, i order to simplif
```suggestion
   * Onboarding and Training: The entire feature flag solution, including API, UI, and SDKs, requires clear and comprehensive documentation, along with easy-to-understand examples, i order to simplify the onboarding process for new developers. It also supports the ongoing training of new team members, ensuring that everyone can effectively use the feature flagging solution.
   
Thank you for reading. Our motivation for writing these principles is to share what we’ve learned building a large-scale feature flag solution with other architects and engineers solving similar challenges. Unleash is open-source, and so are these principles. Have something to contribute? [Open a PR](https://github.com/Unleash/unleash/pulls) or [discussion](https://github.com/orgs/Unleash/discussions) on our Github.
```

2024-08-12 17:31 UTC, ferrantim commented on website/docs/topics/feature-flags/feature-flag-best-practices.md
> +### H3 \- 7\. Make feature flags short-lived. Do not confuse flags with application configuration.[​](https://docs.getunleash.io/topics/feature-flags/feature-flag-best-practices\#7-make-feature-flags
```suggestion
### \- 7\. Make feature flags short-lived. Do not confuse flags with application configuration.[​](https://docs.getunleash.io/topics/feature-flags/feature-flag-best-practices\#7-make-feature-flags-short-lived-do-not-confuse-flags-with-application-configuration)
```

2024-08-12 17:31 UTC, ferrantim commented on website/docs/topics/feature-flags/feature-flag-best-practices.md
> +### H3 \- 8\. Use unique names across all applications. Enforce naming conventions.[​](https://docs.getunleash.io/topics/feature-flags/feature-flag-best-practices\#8-use-unique-names-across-all-appli
```suggestion
### \- 8\. Use unique names across all applications. Enforce naming conventions.[​](https://docs.getunleash.io/topics/feature-flags/feature-flag-best-practices\#8-use-unique-names-across-all-applications-enforce-naming-conventions)
```

2024-08-12 17:31 UTC, ferrantim commented on website/docs/topics/feature-flags/feature-flag-best-practices.md
> +### H3 \- 9\. Choose open by default. Democratize feature flag access.[​](https://docs.getunleash.io/topics/feature-flags/feature-flag-best-practices\#9-choose-open-by-default-democratize-feature-fla
```suggestion
### \- 9\. Choose open by default. Democratize feature flag access.[​](https://docs.getunleash.io/topics/feature-flags/feature-flag-best-practices\#9-choose-open-by-default-democratize-feature-flag-access)
```

2024-08-12 17:31 UTC, ferrantim commented on website/docs/topics/feature-flags/feature-flag-best-practices.md
> +### H3 \- 10\. Do no harm. Prioritize consistent user experience.[​](https://docs.getunleash.io/topics/feature-flags/feature-flag-best-practices\#10-do-no-harm-prioritize-consistent-user-experience)
```suggestion
### \- 10\. Do no harm. Prioritize consistent user experience.[​](https://docs.getunleash.io/topics/feature-flags/feature-flag-best-practices\#10-do-no-harm-prioritize-consistent-user-experience)
```

2024-08-12 17:31 UTC, ferrantim commented on website/docs/topics/feature-flags/feature-flag-best-practices.md
> +### H3 \- 11\. Enable traceability. Make it easy to understand flag evaluation.[​](https://docs.getunleash.io/topics/feature-flags/feature-flag-best-practices\#11-enable-traceability-make-it-easy-to-
```suggestion
### \- 11\. Enable traceability. Make it easy to understand flag evaluation.[​](https://docs.getunleash.io/topics/feature-flags/feature-flag-best-practices\#11-enable-traceability-make-it-easy-to-understand-flag-evaluation)
```

2024-08-12 20:02 UTC, melindafekete commented on website/docs/topics/feature-flags/feature-flag-best-practices.md
> +* [1\. Enable run-time control. Control flags dynamically, not using config files.](https://docs.getunleash.io/topics/feature-flags/feature-flag-best-practices\#1-enable-run-time-control-control-flag
For consistency, I would go for runtime (unhyphenated) for all occurrences on the page

2024-08-15 06:00 UTC, riboflavin commented on website/docs/topics/feature-flags/feature-flag-best-practices.md
> +* Evaluate Locally: Whenever possible, the SDKs or application components should be able to evaluate feature flags locally without relying on external services. This ensures that feature flag evaluat
I went through and tried to make these consistent.

2024-08-16 19:10 UTC, melindafekete commented
Superseded by #7907

2024-08-16 19:10 UTC, closed without merging