Django tutorial + Nav update
Unleash/unleash pull request #7982
Opened 2024-08-26 16:15 UTC by alvinometric

Updating the nav so Django and Rails are both listed under their respective language.

2024-08-27 09:09 UTC, sighphyre requested changes
Nice! Looks like a good start

2024-08-27 09:09 UTC, sighphyre commented on website/docs/feature-flag-tutorials/django/implementing-feature-flags-django.md
> +    url="http://localhost:4242/api/",
I think it's worth just setting the  `refresh_interval` down to something short like 1 second and scrapping the warning about 30 seconds at the end. This is a tutorial, I think the fast updates are nice so long as the user is warned it's not a production ready config.

2024-08-27 09:09 UTC, sighphyre commented on website/docs/feature-flag-tutorials/django/implementing-feature-flags-django.md
> +from UnleashClient import UnleashClient
Starting the client in the view is definitely not sane for a production config. I think that's totally sane for a tutorial and going through a dance of setting up a singleton is probably out of scope here but we should make this clear that this does belong in a singleton and not newed up where ever

2024-08-27 11:27 UTC, melindafekete reviewed
Thanks @alvinometric 🚀

2024-08-27 11:27 UTC, melindafekete commented on website/docs/feature-flag-tutorials/django/implementing-feature-flags-django.md
> +## 3. Setup the Django app
```suggestion
## 3. Set up the Django app
```

2024-08-27 11:27 UTC, melindafekete commented on website/docs/feature-flag-tutorials/django/implementing-feature-flags-django.md
> +#### Setup/seed the database
```suggestion
#### Set up and seed the database
```

2024-08-27 11:27 UTC, melindafekete commented on website/docs/feature-flag-tutorials/django/implementing-feature-flags-django.md
> +-   [3. Setup the Django app](#3-setup-the-django-app)
```suggestion
-   [3. Set up the Django app](#3-set-up-the-django-app)
```

2024-08-27 11:27 UTC, melindafekete commented on website/docs/feature-flag-tutorials/django/implementing-feature-flags-django.md
> +    -   [Setup/seed the database](#setupseed-the-database)
```suggestion
    -   [Set up and seed the database](#set-up-and-seed-the-database)
```

2024-09-02 16:49 UTC, alvinometric commented on website/docs/feature-flag-tutorials/django/implementing-feature-flags-django.md
> +![Create a new feature flag](../ruby/new-ff.png)
I agree, but we do this everywhere. I can make another PR to address that

2024-09-03 06:56 UTC, sighphyre commented on website/docs/feature-flag-tutorials/django/implementing-feature-flags-django.md
> +![Create a new feature flag](../ruby/new-ff.png)
Sure, can't complain if it's an existing pattern

2024-09-03 06:56 UTC, sighphyre approved these changes
:+1:

2024-09-03 07:39 UTC, melindafekete approved these changes

2024-09-03 07:39 UTC, melindafekete commented on website/docs/feature-flag-tutorials/django/implementing-feature-flags-django.md
> +    if  unleash_client.is_enabled("top-3"):
```suggestion
    if unleash_client.is_enabled("top-3"):
```

2024-09-03 07:39 UTC, melindafekete commented on website/docs/feature-flag-tutorials/django/implementing-feature-flags-django.md
> +    posts = Post.objects.order_by('-published_at')[:3] if is_top3 else Post.objects.all()
```suggestion
    posts = Post.objects.order_by('-published_date')[:3] if is_top3 else Post.objects.all()
```

2024-09-04 08:14 UTC, merged